name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: useblacksmith/setup-node@v5
      with:
        node-version: '18'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.9.0

    - name: Install dependencies
      run: pnpm install

    - name: Run linting
      run: pnpm run lint

    - name: Build
      run: pnpm run build

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: pnpm test