name: Publish
on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 10.9.0
      - run: pnpm install --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test
      - run: npx tsx utils/workspace.ts --ensure-consistent
      - run: pnpm --filter="@limetest/core" --filter="@limetest/limetest" --filter="@limetest/mcp" publish --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}